### PR TITLE
Fix css

### PR DESCRIPTION
**Pull request by apreshill**
I'll leave this branch open to do a few more fixes, but this will get us started by:

1. Removing extra css file that was added (it was already built into the theme)
1. Updating the theme to take care of broken logo link in top navbar
1. Making the new event added a bundled event

More to come!

Sorry for lack of documentation ;)

- [x] check event bundles

- [x] Check event archetype to include description in yaml

- [x] Change hex stickers to link to  tidy models.org

- [ ] Maybe choose svg and png

- [ ] Change favicon

- [ ] Delete favicon.ico from lithium

- [x] figure out how to remove logo image

- [x] Figure out errant BY line

- [x] Figure out giant font on index.md 

- [x] make site title mono font (make it a switch?)

- [x] fix code font size in headers ([note to self](https://github.com/rbind/apreshill/commit/bc07090a93349fe9f1b12387c0deeb76eff951b3))

Most will be updated in the actual Hugo theme, to reinstall theme:
```
blogdown::install_theme("rstudio/hugo-tourmaline", update_config = FALSE, force = TRUE)
```

### CODE REVIEW

**Comment by apreshill** [comment]
- [x] Fix mono font though

**Comment by topepo** [comment]
@apreshill How should I resolve those conflicts? I removed the two articles. Should they be restored?

**Comment by apreshill** [comment]
@topepo yea deleting those is just fine- they were carried over from the example site we started working with.

**Comment by apreshill** [comment]
I just added links in the upper navbar for the tm blog versus tv blog so it is easier to see what is where now.

**Pull request merged**
