### PR TITLE
Add text modeling article

### LINKED ISSUE #26: textrecipes vignettes
textrecipes have started to get to a really good spot feature-wise lately. But looking at it the documentation, regarding examples and vignettes, has been lacking quite a bit. I'm planning to deal with those shortcomings the next month or so.

What are the guidelines of where they should be placed? Should I keep them in the textrecipes pkgdown or should I be prepared to have them here? 😄

### PR DESCRIPTION
**Pull request by juliasilge**
Closes #26 

This PR moves the "extra" text analysis article that is [currently in tune](https://tune.tidymodels.org/articles/extras/text_analysis.html) here to `tidymodels.org`. I did some light-to-medium editing of the narrative (not much change to the code). I know we talked about changing the dataset @topepo but I think this one is OK for now, certainly good enough to get the article out of the tune pkgdown site.

For clarity, we don't want the article in the tune pkgdown site anymore because it takes quite a long time to build, longer than we would typically like for something in a pkgdown site. It's a better fit here.

When this is merged in, I will plan to remove this content from tune.

### CODE REVIEW

**Comment by juliasilge** [comment]
Check out 👀 [the preview](https://deploy-preview-197--tidymodels-org.netlify.app/learn/work/tune-text/)

**Comment by topepo** [comment]
Can you change the `glmnet` mixture values from `seq(0, 1, length = 5)` to `c(0.05, 0.25, 0.50, 0.75, 1)`?

**Comment by juliasilge** [comment]
The results look a bit clearer and easier to understand with 0.01 instead of 0.05:

image

I'm going to use that, if that's good with you.

**Comment by juliasilge** [comment]
New version is [now available to preview here](https://deploy-preview-197--tidymodels-org.netlify.app/learn/work/tune-text/)!

**Pull request merged**
