### PR TITLE
Ezgi shortcodes

### PR DESCRIPTION
**Pull request by karaesmen**
Changes column names for find/parsnip tables. 
Comes with quite a bit of change in `static/rmarkdown-libs/datatables-binding/datatables.js`
Used dev version of `DT`

### CODE REVIEW

**Comment by karaesmen** [comment]
Closes #172

**Comment by juliasilge** [comment]
This is looking good! 🙌 I don't see the new, fixed up DT headers here but that was CSS only (not any DT code) so this is OK to merge, correct?

**Comment by juliasilge** [comment]
To be clear, I think "model type" looks just fine and is not too long.

**Comment by apreshill** [comment]
@juliasilge you are right- the new CSS file must have not made it into this branch (it looks like this is called `ezgi_shortcodes` so this branch may have been made last week?). But I do think safe to merge.

**Pull request merged**
