### PR TITLE
Fixed geom_bar

### PR DESCRIPTION
**Pull request by rudeboybert**
In "Statistical analysis of contingency tables" RMarkdown file. Now outputs this:
Rplot

### CODE REVIEW

**Comment by juliasilge** [comment]
I had switched this on purpose and changed "height" to "length" in the text below, to make it easier to read the genotypes (which before were tilted). Is there a reason you prefer the bars to go vertically?

**Comment by juliasilge** [comment]
I was thinking about this again @rudeboybert. Have you not updated ggplot2 in a while? Was this literally not working for you? You can specify `x` and `y` like this as of ggplot2 3.3 or so.

**Comment by rudeboybert** [comment]
@juliasilge I had updated `tidymodels` but not `tidyverse`, hence was using `ggplot2` v3.2.1, hence this was throwing an error for me, hence the PR. Since the horizontal barplot was intentional, please revert.

**Comment by rudeboybert** [comment]
@juliasilge Apologies for not having been more judicious with package versions

**Comment by juliasilge** [comment]
Oh, no problem at all!

**Pull request merged**
