### PR TITLE
v1 of site layout and style

### PR DESCRIPTION
**Pull request by apreshill**
This PR updates the tidymodels.org site with changes to the site layouts (in `layouts/`) and styling (via the `params.toml` file and `static/css/tm.css`). The previous `examples` have been split up into two content sections:

1. `start`- in the upper navbar, accessed via "GET STARTED"
1. `learn`- same as in upper navbar

### CODE REVIEW

**Comment by DavisVaughan** [comment]
This looks great! I'm really impressed!

(I haven't seen this section at all yet, so forgive me if these comments are unrelated to the PR). 

For the learn section, once you get into a single blog post, (for example learn->beginner->K-means), could we show a table of contents on the RHS under contents and upcoming events? I think that would give a nice overview of the post.

For the Get Started section, I'm wondering what the most useful way to structure this is. Right now, once you get into a section (like Building a model), you get that TOC at the top, but you lose it as soon as you scroll down at all. I'm not entirely sure where you could put it though.

One possible thought is to:

- Remove the LHS table of contents with the 4 main getting started sections
- Add a TOC to the RHS that would be specific to that post (this would also align it with the Learn posts a bit more)
- At the bottom of the post (and maybe the top too), have a link that goes to the "next section" and "previous section" to move through the 4 main sections.

I have absolutely no idea how much work all of that would be, so feel free to ignore if those are ridiculous requests 😬

**Comment by juliasilge** [comment]
I also think this is looking fantastic! Definitely ready for us to move forward. The packages page is looking so great, and I think separating out "getting started" and "learn" is the right call for now.

I'm going to throw in my opinion here (it's somewhat different than @DavisVaughan): I think the sticky LHS info on "Getting Started" is important and helpful (I'm neutral on LH vs. RH but LH *is* nice because it is different than anything else we have and thus says: "pay attention"). I would very much like to see us keep that, and IMO it's a higher priority than using sticky screen real estate for individual TOC for specific articles. The fact that it is sticky so learners can tell where they are in the overall arc of learning is valuable.

💡Can the "getting started" article be highlighted or a different color to indicate which one the user is currently on? i.e. when the user is viewing "Evaluate your model with resampling" that section on the left sticky bar is visually called out. 

I am fine with the article-level TOCs being different between "getting started" and "learn" (i.e. at the top with "getting started" and on the right under "Contents" in "learn") since "getting started" is more like a sequence and "learn" is more like a collection. I don't see the TOC content right now in "learn" and I am guessing that is still todo? The other thing I would like to see on the right in "learn" is some kind of nice box ◻️ with a statement of the learning objective:

> In this article, learn how to use nested resampling to evaluate your model.

I don't believe we are adding this info anywhere right now but we definitely want to.

**Comment by apreshill** [comment]
Hi @juliasilge and @DavisVaughan,

Thanks for the feedback! We started with overall site structure and big design items like colors and fonts; now comes lots of work together to style the actual content so these are helpful to start tracking. In the current branch, I intentionally didn't change any files or content- just style and layout so we could start from the same place as the `examples` branch and change one thing at a time.

I'll try to distill some elements here and hope that we can schedule a call to discuss some of the other trickier bits.

1. For TOCs under `learn`, this is same as tidyverse.org (and the education site). It depends on using .Rmarkdown files, so currently all learn files are .Rmd and you don't see any Contents as a result. Drawback is you cannot use HTML widgets in .Rmarkdown files. Do you think all of the .Rmds in `learn` can be converted to .Rmarkdown? If not, @dcossyleon and I can work on using CSS to better style the TOC using divs (see: http://desiree.rbind.io/post/2019/making-tip-boxes-with-bookdown-and-rmarkdown/); we have also discussed the possibility of using a teensy bit of JavaScript to move .Rmd TOC's to the right (see: https://github.com/tidymodels/tidymodels.org/issues/17)

1. Related to those divs, I want @dcossyleon to design some custom divs for learning objectives (as @juliasilge suggested) and a few other sections. Again, no Hugo so pretty quick CSS tweaks to do.

1. Having a active menu items for the `start` section is on our [Hugo to-do list](https://github.com/tidymodels/tidymodels.org/issues/18) and [CSS to-do list](https://github.com/tidymodels/tidymodels.org/issues/17); agreed is high priority. I envision something like what @dcossyleon did for [Stat545](https://stat545.com/).

1. A bottom link in `start` to the next article can def be done as I did [here](https://education.rstudio.com/learn/beginner/); added to the [Hugo to-do list](https://github.com/tidymodels/tidymodels.org/issues/18).

More generally, I'm open to 2 content organization structures going forward:

1. Separate `start` and `learn` sections. This is how I have the site currently set up, as it took the most Hugo layout work. If one section (`start`) has a sequence and different goals for users, I'd strongly prefer to make sure the layout looks clearly different from articles in `learn`. Otherwise, it will be confusing for users to remember where they are, so I would recommend against having 2 content sections with the same layout.

1. One `learn` section; combine with current `start` section. If we feel like we want to make all articles look the same, I would put them in the same content section to avoid confusing users. This would also mean that we would need to standardize a lot of the article content/structures, so bigger changes than just aesthetics. I currently prefer (1), but with enough work to the other articles in `learn` this could still work.

Please let me know how you want to move forward with this specific PR, as it definitely isn't final and needs work that will take more time. My working assumption was that we needed to rip the bandaid off and get to a common file structure early so we could all keep making progress, but Desiree and I can just keep hammering away at this branch over the next few weeks as well. We have a webinar to prep for next Tuesday, so will be returning to work on the site together next week.

**Comment by topepo** [comment]
> Please let me know how you want to move forward with this specific PR

I'd say merge it and we can pick-off bits at a time. I also think that we can evolve it a bit once it is launched based on broader feedback. Perfection is the enemy of the good (or, in this case, great).

**Pull request merged**
