### PR TITLE
Update site with new CRAN versions

### PR DESCRIPTION
**Pull request by juliasilge**
This PR (draft for now) will update the site with

- new CRAN versions of packages
- removing tidyr (now loaded with tiydmodels)
- fix for `cli.width`, closing #133 
- ~adding back in the partykit plot~ STILL NOT WORKING
- updated developer articles
- adding new "adjacent" packages, closing #106

and possibly other things as I come across them.

### CODE REVIEW

**Comment by juliasilge** [comment]
@DavisVaughan Can you check out how I changed [`/learn/develop/metrics`](https://deploy-preview-184--tidymodels-org.netlify.app/learn/develop/metrics/) for changes in yardstick?

**Comment by DavisVaughan** [comment]
@juliasilge for `mse()`, you can now use `new_numeric_metric()` on it to take care of adding the class
https://github.com/tidymodels/yardstick/blob/430912afa5e9e30632f5ac5a4cd205b7fcf9416f/vignettes/custom-metrics.Rmd#L116-L120

This makes the "using custom metrics" part much simpler, since everything is handled for you
https://github.com/tidymodels/yardstick/blob/430912afa5e9e30632f5ac5a4cd205b7fcf9416f/vignettes/custom-metrics.Rmd#L463-L470

Otherwise the edits from this commit look good https://github.com/tidymodels/tidymodels.org/pull/184/commits/3d0b84be2767621d3bfb1c1cd3a408969a5028ae!

(The yardstick pkgdown github actions build is broken so you wouldnt have been able to see that on the pkgdown site. ill go fix that)

**Comment by juliasilge** [comment]
Thanks @DavisVaughan; [got that now here](https://deploy-preview-184--tidymodels-org.netlify.app/learn/develop/metrics/#using-custom-metrics).

Both you and @topepo, want to check out what I added to [/learn/develop/models](https://deploy-preview-184--tidymodels-org.netlify.app/learn/develop/models/#pro-tips-what-ifs-exceptions-faq-and-minutiae) about predictor encodings? It is a paragraph in the FAQ/minutae section, since the example model in this article uses the default encodings.

**Comment by DavisVaughan** [comment]
@juliasilge I think that paragraph looks good. Linking to the blog post for more details is a nice touch.

**Review by topepo — APPROVED** [review]

**Pull request merged**
