### PR TITLE
Edits to content in /learn and /start

### PR DESCRIPTION
**Pull request by juliasilge**
**WIP for now**

Edits to articles in `/learn` and `/start` for content, section titles (how do they render in sidebar?), etc.

### CODE REVIEW

**Comment by juliasilge** [comment]
## Notes

- `make_ames()` is giving warnings; I submitted a PR in topepo/AmesHousing#6
- I thought keras was installed and working on my machine but apparently not so I didn't render `parsnip-nnet` for now
- The new dplyr does something real bad 😬 to the tuning functions (noticed in `tune-svm`). Have not yet diagnosed but all models fail all the time.

**Comment by apreshill** [comment]
Hi @juliasilge,

While you are in these articles, do you think you could add one-sentence descriptions to the YAML of the `start/` articles (these were the "learning objectives" for the `learn/` articles)? I think they are very helpful, and they show up currently as blank on the listing pages by packages:

https://deploy-preview-55--goofy-kowalevski-f8316d.netlify.com/tags/parsnip/
Screen Shot 2020-04-07 at 4 17 44 PM

(if it is easier I can move this to an issue instead, just let me know...)

**Comment by juliasilge** [comment]
Yes, will do @apreshill! Now is a good time.

**Comment by topepo** [comment]
In [`https://deploy-preview-55--goofy-kowalevski-f8316d.netlify.com/functions/parsnip/`](https://deploy-preview-55--goofy-kowalevski-f8316d.netlify.com/functions/parsnip/) can you have the link there point to the `parsnip` custom model page here?

**Comment by juliasilge** [comment]
Probably that change should be made in #54 (not this one) since @apreshill is editing those files.

**Comment by juliasilge** [comment]
My results from `serve_site()` have some warnings due to the new tibble FYI. We are working to address these in tidymodels/recipes#490.

**Comment by juliasilge** [comment]
This PR is now ready to merge!

**Review by apreshill — APPROVED** [review]
This looks awesome! Thank you so much for all these updates.

**Pull request merged**
