### PR TITLE
Warning box RE: parallel processing + new parsnip model

### LINKED ISSUE #157: make a note in parsnip new model instructions
See tidymodels/tune#205

We need to explicitly note that, if parallel processing is going to be used with `tune`, the new model and/or engine must be in a package and registered when loaded.

### PR DESCRIPTION
**Pull request by juliasilge**
This PR adds one of the fancy new ✨ boxes ✨  to close #157.

### CODE REVIEW

**Comment by juliasilge** [comment]
Check out [what it looks like here](https://deploy-preview-158--tidymodels-org.netlify.app/learn/develop/models/#your-model-tuning-parameters-and-you).

**Comment by apreshill** [comment]
I ❤️ this!!

**Comment by topepo** [comment]
I accidentally committed a different fix straight to master. Just reverted it. In mine, I added a link to the issue: 

> In order to use a new model or engine in the broader `tidymodels` infrastructure, we recommend the model definition declarations (e.g. `set_new_model()` and similar) reside in a new package. If left in a simple R script, the new method may not work with the tune package (see [this issue](https://github.com/tidymodels/tune/issues/205#issuecomment-626414994)).

Too much detail?

**Comment by juliasilge** [comment]
I don't like the idea of linking to a closed issue on this site that is meant to be long-lasting documentation, but I took most of your framing there and [updated the warning box](https://deploy-preview-158--tidymodels-org.netlify.app/learn/develop/models/#add-parsnip-models-to-another-package). Take a look and see what you think!

**Pull request merged**
