### PR TITLE
Julia's edits, for before Monday's tidyverse meeting

### PR DESCRIPTION
**Pull request by juliasilge**
I plan to get more done on this PR in the next day, then we hope to get this + the developer articles merged before presenting at the tidyverse meeting Monday. 

@apreshill Is that doable for you? Would it work if we call a deadline for any new changes to be merged EOD Friday?

### CODE REVIEW

**Comment by topepo** [comment]
@juliasilge Can you edit the yaml at the top to use package names in `tags` and tasks in `categories` etc?

**Comment by apreshill** [comment]
@juliasilge yes I can handle through Friday end of day for sure. Thanks for asking :)

**Comment by juliasilge** [comment]
The tuning example *does* currently use dials because it was super awkward without it, but we can revisit that if necessary.

**Comment by juliasilge** [comment]
Let's call this PR done for Monday's meeting. @apreshill merge at your convenience.

**Pull request merged**
