### PR TITLE
Another round of edits throughout

### PR DESCRIPTION
**Pull request by juliasilge**
I'm going to work on edits here through Wed for our meeting on Thursday. WIP for now but I will ping when I'm done.

### CODE REVIEW

**Comment by juliasilge** [comment]
Let's use these titles for now for the four 4️⃣ `learn` sections:

- Perform statistical analysis
- Create robust models
- Tune, compare, and work with your models
- Develop custom modeling tools

**Comment by juliasilge** [comment]
I believe ready to go now @apreshill. Take a look and merge at your convenience.

**Comment by apreshill** [comment]
Perfect, thank you! I will take a look tonight. In the meantime, may I ask for a one word to go along with each of these, which will be the name of the content folder, and appear in the urls?


    Perform statistical analysis --> tidymodels.org/learn/____/
    Create robust models --> tidymodels.org/learn/____/
    Tune, compare, and work with your models --> tidymodels.org/learn/____/
    Develop custom modeling tools --> tidymodels.org/learn/____/

**Comment by juliasilge** [comment]
Let's do this (feedback welcome):

```
Perform statistical analysis --> tidymodels.org/learn/statistics/
Create robust models --> tidymodels.org/learn/models/
Tune, compare, and work with your models --> tidymodels.org/learn/work/
Develop custom modeling tools --> tidymodels.org/learn/developer/
```

**Comment by apreshill** [comment]
Adding this here:

```
## Perform statistical analysis `/statistics/`
​
- broom + dplyr (rename)
- k-mean clustering (rename)
- tidy bootstrapping (rename)
- infer basics
- infer tables
​
## Create robust models `/models/`
​
- using parsnip: regression
- using parsnip: classification
- subsampling for class imbalance
- modeling time series with tidy resampling
- multivariate modeling
​
## Tune, compare, and work with your models `/work/`
​
- model tuning with grid search
- nested resampling
- Bayesian optimization
​
## Develop custom modeling tools `/developer/`
​
- recipe step
- parsip model
- yardstick metrics
- tuning parameter function
```

**Comment by juliasilge** [comment]
The only thing I would change in order, after editing them, is to switch the two "using parsnip" articles.

**Comment by juliasilge** [comment]
OK, and maybe put "subsampling for class imbalance" third in that section.

**Comment by apreshill** [comment]
Thanks- are the edits right now?

**Comment by juliasilge** [comment]
Yes, looks good 👍

**Pull request merged**
